/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportAppRouteImport } from './routes/ReportApp'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as CouncillorIndexRouteImport } from './routes/councillor/index'
import { Route as CouncillorDashboardRouteImport } from './routes/councillor/dashboard'
import { Route as CouncillorMunicipalityIdWardNumberRouteImport } from './routes/councillor/$municipalityId.$wardNumber'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportAppRoute = ReportAppRouteImport.update({
  id: '/ReportApp',
  path: '/ReportApp',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const CouncillorIndexRoute = CouncillorIndexRouteImport.update({
  id: '/councillor/',
  path: '/councillor/',
  getParentRoute: () => rootRouteImport,
} as any)
const CouncillorDashboardRoute = CouncillorDashboardRouteImport.update({
  id: '/councillor/dashboard',
  path: '/councillor/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CouncillorMunicipalityIdWardNumberRoute =
  CouncillorMunicipalityIdWardNumberRouteImport.update({
    id: '/councillor/$municipalityId/$wardNumber',
    path: '/councillor/$municipalityId/$wardNumber',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ReportApp': typeof ReportAppRoute
  '/admin': typeof AdminRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/councillor/dashboard': typeof CouncillorDashboardRoute
  '/councillor/': typeof CouncillorIndexRoute
  '/councillor/$municipalityId/$wardNumber': typeof CouncillorMunicipalityIdWardNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ReportApp': typeof ReportAppRoute
  '/admin': typeof AdminRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/councillor/dashboard': typeof CouncillorDashboardRoute
  '/councillor': typeof CouncillorIndexRoute
  '/councillor/$municipalityId/$wardNumber': typeof CouncillorMunicipalityIdWardNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ReportApp': typeof ReportAppRoute
  '/admin': typeof AdminRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/councillor/dashboard': typeof CouncillorDashboardRoute
  '/councillor/': typeof CouncillorIndexRoute
  '/councillor/$municipalityId/$wardNumber': typeof CouncillorMunicipalityIdWardNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ReportApp'
    | '/admin'
    | '/privacy'
    | '/terms'
    | '/councillor/dashboard'
    | '/councillor/'
    | '/councillor/$municipalityId/$wardNumber'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ReportApp'
    | '/admin'
    | '/privacy'
    | '/terms'
    | '/councillor/dashboard'
    | '/councillor'
    | '/councillor/$municipalityId/$wardNumber'
  id:
    | '__root__'
    | '/'
    | '/ReportApp'
    | '/admin'
    | '/privacy'
    | '/terms'
    | '/councillor/dashboard'
    | '/councillor/'
    | '/councillor/$municipalityId/$wardNumber'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReportAppRoute: typeof ReportAppRoute
  AdminRoute: typeof AdminRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  CouncillorDashboardRoute: typeof CouncillorDashboardRoute
  CouncillorIndexRoute: typeof CouncillorIndexRoute
  CouncillorMunicipalityIdWardNumberRoute: typeof CouncillorMunicipalityIdWardNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ReportApp': {
      id: '/ReportApp'
      path: '/ReportApp'
      fullPath: '/ReportApp'
      preLoaderRoute: typeof ReportAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/councillor/': {
      id: '/councillor/'
      path: '/councillor'
      fullPath: '/councillor/'
      preLoaderRoute: typeof CouncillorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/councillor/dashboard': {
      id: '/councillor/dashboard'
      path: '/councillor/dashboard'
      fullPath: '/councillor/dashboard'
      preLoaderRoute: typeof CouncillorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/councillor/$municipalityId/$wardNumber': {
      id: '/councillor/$municipalityId/$wardNumber'
      path: '/councillor/$municipalityId/$wardNumber'
      fullPath: '/councillor/$municipalityId/$wardNumber'
      preLoaderRoute: typeof CouncillorMunicipalityIdWardNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReportAppRoute: ReportAppRoute,
  AdminRoute: AdminRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  CouncillorDashboardRoute: CouncillorDashboardRoute,
  CouncillorIndexRoute: CouncillorIndexRoute,
  CouncillorMunicipalityIdWardNumberRoute:
    CouncillorMunicipalityIdWardNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
