/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportAppRouteImport } from './routes/ReportApp'
import { Route as CouncillorRouteImport } from './routes/councillor'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportAppRoute = ReportAppRouteImport.update({
  id: '/ReportApp',
  path: '/ReportApp',
  getParentRoute: () => rootRouteImport,
} as any)
const CouncillorRoute = CouncillorRouteImport.update({
  id: '/councillor',
  path: '/councillor',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ReportApp': typeof ReportAppRoute
  '/councillor': typeof CouncillorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ReportApp': typeof ReportAppRoute
  '/councillor': typeof CouncillorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ReportApp': typeof ReportAppRoute
  '/councillor': typeof CouncillorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ReportApp' | '/councillor'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ReportApp' | '/councillor'
  id: '__root__' | '/' | '/ReportApp' | '/councillor'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReportAppRoute: typeof ReportAppRoute
  CouncillorRoute: typeof CouncillorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ReportApp': {
      id: '/ReportApp'
      path: '/ReportApp'
      fullPath: '/ReportApp'
      preLoaderRoute: typeof ReportAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/councillor': {
      id: '/councillor'
      path: '/councillor'
      fullPath: '/councillor'
      preLoaderRoute: typeof CouncillorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReportAppRoute: ReportAppRoute,
  CouncillorRoute: CouncillorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
